### ISSUE TITLE
[enhancement] R2730DB/RC10D1 

### ISSUE THREAD

**Issue by norbicki** [norbicki/Edifier-RC10D1#1]
Thread moved from [Edifier-RC10E](https://github.com/norbicki/Edifier-RC10E/issues/1)

[Check it out. ](https://github.com/norbicki/Edifier-RC10D1/tree/master/app/release)

**Comment by Moonstone3010** [comment]
Wow, that escalated quickly : )
Everything works as it should. I look forward to seeing the app in the F-Droid repo.
I think you should consider adding a 'make a donation' link in the readme.
